export const FETCH_SUM_VALUE_DATA_SUCCESS = 'FETCH_SUM_VALUE_DATA_SUCCESS';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const TOGGLE_ADD_BLOCK = 'TOGGLE_ADD_BLOCK';
export const ADD_TABLE_BLOCK_ROW = 'ADD_TABLE_BLOCK_ROW';
export const TOGGLE_EDIT_BLOCK = 'TOGGLE_EDIT_BLOCK';