export const GET_LOCATION = 'GET_LOCATION';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_UNITS_FROM_LOCATION = 'GET_UNITS_FROM_LOCATION';
export const GET_KEYS_FROM_UNIT = 'GET_KEYS_FROM_UNIT';
export const FETCH_LOCATION_DATA_SUCCESS = 'FETCH_LOCATION_DATA_SUCCESS';